version: '3'

services:
  prometheus:
    image: m.daocloud.io/docker.io/prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/targets:/etc/prometheus/targets
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9190:9090"
    restart: unless-stopped

  grafana:
    image: m.daocloud.io/docker.io/grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=ohth7Gu2Cheez4gi
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    ports:
      - "3100:3000"
    restart: unless-stopped
    depends_on:
      - prometheus

  chatgpt-monitor:
    build: ./monitor
    container_name: chatgpt-monitor
    ports:
      - "9191:3000"
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data: