global:
  scrape_timeout: 30s
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'chatgpt'
    metrics_path: '/metrics'
    scheme: 'https'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/chatgpt-targets.json
        refresh_interval: 1m